import { Product, CarouselSlide } from './types'

export const mockSlides: CarouselSlide[] = [
  {
    id: '1',
    title: 'Nova Coleção Verão',
    subtitle: 'Looks poderosos para treinos ainda mais incríveis',
    cta_text: 'Ver Lançamentos',
    cta_link: '/produtos?filter=new',
    image_url: 'https://picsum.photos/seed/gym1/1400/600',
    badge: 'Novo',
    active: true,
    order_index: 1,
  },
  {
    id: '2',
    title: 'Até 40% OFF',
    subtitle: 'Promoção especial em conjuntos selecionados',
    cta_text: 'Aproveitar Oferta',
    cta_link: '/produtos?filter=promo',
    image_url: 'https://picsum.photos/seed/gym2/1400/600',
    badge: 'Promoção',
    active: true,
    order_index: 2,
  },
  {
    id: '3',
    title: 'Leggings Premium',
    subtitle: 'Conforto e estilo do aquecimento ao cooldown',
    cta_text: 'Explorar',
    cta_link: '/produtos?category=legging',
    image_url: 'https://picsum.photos/seed/gym3/1400/600',
    badge: 'Destaque',
    active: true,
    order_index: 3,
  },
]

export const mockProducts: Product[] = [
  {
    id: '1',
    name: 'Legging Sculpt Coral',
    description: 'Legging de alta compressão com tecido respirável. Perfeita para treinos intensos.',
    price: 149.90,
    original_price: 199.90,
    category: 'legging',
    sizes: ['P', 'M', 'G', 'GG'],
    colors: ['Coral', 'Preto', 'Nude'],
    image_url: 'https://picsum.photos/seed/prod1/400/500',
    is_featured: true,
    is_new: false,
    is_promotion: true,
    discount_percent: 25,
    created_at: '2024-01-01',
    stock: 15,
  },
  {
    id: '2',
    name: 'Top Fit Terracota',
    description: 'Top esportivo com bojo removível. Suporte médio ideal para yoga e pilates.',
    price: 89.90,
    category: 'top',
    sizes: ['P', 'M', 'G'],
    colors: ['Terracota', 'Rosa', 'Branco'],
    image_url: 'https://picsum.photos/seed/prod2/400/500',
    is_featured: true,
    is_new: true,
    is_promotion: false,
    created_at: '2024-01-15',
    stock: 20,
  },
  {
    id: '3',
    name: 'Conjunto Fire',
    description: 'Conjunto top + legging em tecido premium. Look completo para a academia.',
    price: 219.90,
    original_price: 279.90,
    category: 'conjunto',
    sizes: ['P', 'M', 'G', 'GG'],
    colors: ['Coral', 'Vinho'],
    image_url: 'https://picsum.photos/seed/prod3/400/500',
    is_featured: true,
    is_new: true,
    is_promotion: true,
    discount_percent: 21,
    created_at: '2024-02-01',
    stock: 8,
  },
  {
    id: '4',
    name: 'Shorts Energy',
    description: 'Shorts de treino com bolso lateral e cós elástico. Liberdade de movimento total.',
    price: 79.90,
    category: 'shorts',
    sizes: ['P', 'M', 'G'],
    colors: ['Preto', 'Coral', 'Nude'],
    image_url: 'https://picsum.photos/seed/prod4/400/500',
    is_featured: false,
    is_new: true,
    is_promotion: false,
    created_at: '2024-02-10',
    stock: 25,
  },
  {
    id: '5',
    name: 'Calça Wide Leg',
    description: 'Calça wide leg estilosa para o pós-treino. Conforto sem abrir mão do estilo.',
    price: 169.90,
    category: 'calça',
    sizes: ['P', 'M', 'G', 'GG'],
    colors: ['Nude', 'Terracota', 'Branco'],
    image_url: 'https://picsum.photos/seed/prod5/400/500',
    is_featured: false,
    is_new: false,
    is_promotion: false,
    created_at: '2024-01-20',
    stock: 12,
  },
  {
    id: '6',
    name: 'Macacão Power',
    description: 'Macacão esportivo all-in-one. Praticidade e elegância para qualquer treino.',
    price: 249.90,
    original_price: 299.90,
    category: 'macacão',
    sizes: ['P', 'M', 'G'],
    colors: ['Preto', 'Vinho'],
    image_url: 'https://picsum.photos/seed/prod6/400/500',
    is_featured: true,
    is_new: false,
    is_promotion: true,
    discount_percent: 17,
    created_at: '2024-01-05',
    stock: 6,
  },
  {
    id: '7',
    name: 'Top Nadador Bloom',
    description: 'Top nadador com alças cruzadas. Design exclusivo e suporte firme.',
    price: 99.90,
    category: 'top',
    sizes: ['P', 'M', 'G', 'GG'],
    colors: ['Rosa', 'Coral', 'Nude'],
    image_url: 'https://picsum.photos/seed/prod7/400/500',
    is_featured: false,
    is_new: true,
    is_promotion: false,
    created_at: '2024-02-15',
    stock: 18,
  },
  {
    id: '8',
    name: 'Jaqueta Treino Zip',
    description: 'Jaqueta leve com zíper completo. Perfeita para o inverno e dias mais frescos.',
    price: 189.90,
    category: 'jaqueta',
    sizes: ['P', 'M', 'G', 'GG'],
    colors: ['Terracota', 'Preto', 'Bege'],
    image_url: 'https://picsum.photos/seed/prod8/400/500',
    is_featured: false,
    is_new: false,
    is_promotion: false,
    created_at: '2024-01-10',
    stock: 10,
  },
]
